In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SpatialDropout1D, Bidirectional
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

### 데이터 처리

In [3]:
data = pd.read_csv('data/custom_train.csv')


In [4]:
label_dict = {
    '협박 대화': 0,
    '갈취 대화': 1,
    '직장 내 괴롭힘 대화': 2,
    '기타 괴롭힘 대화': 3,
    '일반 대화': 4
}

data['label'] = data['class'].map(label_dict)

In [5]:
import re

def preprocess_sentence(sentence):
    # 단어와 구두점(punctuation) 사이의 거리를 만듭니다.
    # 예를 들어서 "I am a student." => "I am a student ."와 같이
    # student와 온점 사이에 거리를 만듭니다.
    sentence = sentence.replace("\n", "")         # 구분자
    sentence = sentence.replace("\r", "")         # 구분자
    sentence = re.sub(r"([?.!,])", r" \1 ", sentence)
    sentence = re.sub(r'[" "]+', " ", sentence)

    # (a-z, A-Z,가-힣,0-9, ".", "?", "!", ",")를 제외한 모든 문자를 공백인 ' '로 대체합니다.
    sentence = re.sub(r"[^a-zA-Z가-힣0-9\.\?\!,]"," ",sentence)
    sentence = sentence.strip()
    return sentence

In [6]:
data['conversation'] = data['conversation'].apply(preprocess_sentence)

In [7]:
data_prepcocessed = data.copy()

In [9]:
# 파라미터

MAX_WORDS_LSTM = 5000
MAX_LEN_LSTM = 100

In [10]:
tokenizer = Tokenizer(num_words=MAX_WORDS_LSTM, lower=True)
tokenizer.fit_on_texts(data['conversation'].values)

X_train = tokenizer.texts_to_sequences(data['conversation'].values)
X_train = pad_sequences(X_train, maxlen=MAX_LEN_LSTM)

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(data['label']) # label로 주어 올바른 순서로 훈련

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

y_train = tf.keras.utils.to_categorical(y_train, num_classes=len(np.unique(y_train)))
y_test = tf.keras.utils.to_categorical(y_test, num_classes=len(np.unique(y_test)))

### fasttext

In [11]:
# 파라미터
EPOCH_FT = 100
BUCKET_FT = 20000
NGRAM_FT = 2
DIM_FT = 100

In [12]:
def add_label(x):
    label = x['label']
    return f'''__label__{label}    {x['conversation']}'''
    

add_label_text = data_prepcocessed.apply(add_label, axis=1)


In [13]:
file_path = 'input_fasttext_conversation.txt'

with open(file_path, 'w', encoding='utf8') as f:
    f.write('\n'.join(add_label_text))

In [14]:
# ! pip install fasttext

In [15]:
import fasttext

model_ft = fasttext.train_supervised(input=file_path,
                                  epoch=EPOCH_FT,
                                  bucket = BUCKET_FT,
                                  lr = 1
                                  wordNgrams=NGRAM_FT,
                                  dim=DIM_FT,
                                  )

Read 0M words
Number of words:  72778
Number of labels: 5
Progress: 100.0% words/sec/thread: 1073848 lr:  0.000000 avg.loss:  0.027765 ETA:   0h 0m 0s


### BiLSTM

In [16]:
model_lstm = Sequential()
model_lstm.add(Embedding(MAX_WORDS_LSTM, 128, input_length=MAX_LEN_LSTM))
model_lstm.add(SpatialDropout1D(0.2))
model_lstm.add(Bidirectional(LSTM(64, dropout=0.2, recurrent_dropout=0.2)))
model_lstm.add(Dense(64, activation='relu'))
model_lstm.add(Dense(len(np.unique(data['class'])), activation='softmax'))

model_lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model_lstm.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 128)          640000    
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, 100, 128)          0         
_________________________________________________________________
bidirectional (Bidirectional (None, 128)               98816     
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 325       
Total params: 747,397
Trainable params: 747,397
Non-trainable params: 0
_________________________________________________________________
None


In [17]:
EPOCHS_LSTM = 1
BATCH_SIZE_LSTM = 64

history = model_lstm.fit(X_train, y_train, 
                    epochs=EPOCHS_LSTM, 
                    batch_size=BATCH_SIZE_LSTM, 
                    validation_split=0.2, 
                    callbacks=[tf.keras.callbacks.EarlyStopping(
                        monitor='val_loss', patience=3, min_delta=0.0001)])

51/51 [==============================] - 44s 755ms/step - loss: 1.4234 - accuracy: 0.3518 - val_loss: 1.1272 - val_accuracy: 0.4851


### tranformer

In [18]:
import transformer

In [19]:
# 파라미터
NUM_LAYERS = 12 # 인코더와 디코더의 층의 개수 
D_MODEL = 128 # 인코더와 디코더 내부의 입/출력의 고정 차원
NUM_HEADS = 4 # 멀티 헤드 어텐션에서의 헤드 수 
UNITS = 256 # 피드 포워드 신경망의 은닉층의 크기
DROPOUT = 0.1 # 드롭아웃의 비율

NUM_CLASSES = len(data['class'].unique())  #레이블 수
VOCAB_SIZE = MAX_WORDS_LSTM #단어사전 크기
MAX_LENGTH = X_train.shape[1] # maxlen

In [20]:
model= transformer.transformer(
    vocab_size=VOCAB_SIZE,
    num_layers=NUM_LAYERS,
    units=UNITS,
    d_model=D_MODEL,
    num_heads=NUM_HEADS,
    num_classes=NUM_CLASSES,
    dropout=DROPOUT)

In [22]:
EPOCHS = 1
BATCH_SIZE = 64

model.compile(optimizer='adam',
              loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train,
                    y_train,
                    epochs=EPOCHS,
                    batch_size=BATCH_SIZE,
                    validation_data=(X_test, y_test),
                    verbose=1)

64/64 [==============================] - 23s 149ms/step - loss: 1.7568 - accuracy: 0.2010 - val_loss: 1.6398 - val_accuracy: 0.1911


## 앙상블

In [23]:
test = pd.read_csv('data/custom_test.csv')


In [24]:
test['conversation'] = test['conversation'].apply(preprocess_sentence)
tokenizer.fit_on_texts(test['conversation'].values)

test_input = tokenizer.texts_to_sequences(test['conversation'].values)
test_input = pad_sequences(test_input, maxlen=MAX_LEN_LSTM)

In [26]:
pred_ft =  model_ft.predict(list(test['conversation']), k=-1)
pred_lstm = model_lstm.predict(test_input)
pred_transformer = model.predict(test_input)

In [29]:
pred_ft[1]

[array([5.2496785e-01, 3.4639001e-01, 1.2714981e-01, 1.3219727e-03,
        2.2040245e-04], dtype=float32),
 array([9.9948066e-01, 5.0623523e-04, 3.0762898e-05, 2.1708218e-05,
        1.0749781e-05], dtype=float32),
 array([9.9992251e-01, 9.7450313e-05, 1.0043404e-05, 1.0027095e-05,
        1.0004811e-05], dtype=float32),
 array([5.5894393e-01, 4.1012585e-01, 2.5148874e-02, 5.3116055e-03,
        5.1972631e-04], dtype=float32),
 array([9.8669928e-01, 9.2267236e-03, 2.2702143e-03, 1.0077128e-03,
        8.4620371e-04], dtype=float32),
 array([9.9956197e-01, 4.0896487e-04, 3.9540824e-05, 2.9543397e-05,
        1.0028864e-05], dtype=float32),
 array([9.7015458e-01, 2.7741965e-02, 1.9332877e-03, 1.8708149e-04,
        3.3122109e-05], dtype=float32),
 array([9.9403399e-01, 5.9001660e-03, 9.4945724e-05, 1.0986574e-05,
        1.0002102e-05], dtype=float32),
 array([9.9373585e-01, 6.1234613e-03, 1.6465840e-04, 1.5904610e-05,
        1.0088002e-05], dtype=float32),
 array([1.00000679e+00, 1.29

In [30]:
pred = pred_ft[1] + pred_lstm + pred_transformer

predicted_classes = np.argmax(pred, axis=1)

## 제출

In [31]:
sub = pd.read_csv("data/new_submission.csv")
sub['class']=predicted_classes
# sub.to_csv('data/sub.csv')

In [32]:
sub

file_name  class
0       t_000      0
1       t_001      0
2       t_002      0
3       t_003      4
4       t_004      0
..        ...    ...
495     t_495      0
496     t_496      0
497     t_497      0
498     t_498      0
499     t_499      0

[500 rows x 2 columns]